# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-12 22:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.BigIntegerField()),
                ('unit_price', models.FloatField()),
                ('count', models.IntegerField()),
                ('unit_type', models.CharField(max_length=255)),
                ('delivery_date', models.BigIntegerField()),
                ('productType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.ProductType')),
            ],
        ),
    ]
