# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-12 22:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_adminoffer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produceroffer',
            old_name='modifiable',
            new_name='editable',
        ),
        migrations.RenameField(
            model_name='produceroffer',
            old_name='stage',
            new_name='state',
        ),
    ]
