# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-13 17:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20171012_1732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment',
        ),
        migrations.RemoveField(
            model_name='order_item',
            name='product',
        ),
        migrations.AddField(
            model_name='order_item',
            name='offer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.AdminOffer'),
        ),
    ]
