# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-20 22:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_producttype_producer'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumer',
            name='type',
            field=models.CharField(default='CLIENTE', max_length=15),
        ),
    ]
