# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-25 02:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_consumer_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='state',
            field=models.TextField(default='PENDIENTE'),
        ),
    ]
