# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-30 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_order_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sales_Parameters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profit_margin', models.FloatField()),
            ],
        ),
    ]
